version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    command: ["npm", "start"]

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
